### ISSUE TITLE
java error on server startup

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#1]
Tried version v4.0 the first time with 2 existing courses already configued and working from v3.7. The server starts ok the first time, although I get "you are in the wrong world" if I try to join a course. If you then stop/start the server, you get this error (like its trying to insert the same course details into the DB again):

[22:57:29 INFO]: [Parkour] Enabling Parkour v4.0
[22:57:29 WARN]: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column name is not unique)
[22:57:29 WARN]:        at org.sqlite.DB.newSQLException(DB.java:383)
[22:57:29 WARN]:        at org.sqlite.DB.newSQLException(DB.java:387)
[22:57:29 WARN]:        at org.sqlite.DB.execute(DB.java:342)
[22:57:29 WARN]:        at org.sqlite.DB.executeUpdate(DB.java:363)
[22:57:29 WARN]:        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[22:57:29 WARN]:        at me.A5H73Y.Parkour.Utilities.DatabaseMethods.insertCourse(DatabaseMethods.java:129)

Full error is here:
http://pastebin.com/46uthxnF

**Comment by A5H73Y** [comment]
Hello, thank you for reporting this issue.
This is strange as you've posted this as I've had this problem appear locally and I can't seem to find the problem. I will fix and update as soon as I can! 
The "You are in the wrong world" error is a configurable property in the config.yml, but as you're the third person to complain about that, I will default it to disabled.
Thanks again

**Comment by steve4744** [comment]
Hi, that will be great - thanks. Happy to test any updated code.

**Comment by A5H73Y** [comment]
I found the fix, It was part of my upgrade code.

http://parkour.netne.net/downloads.html
