### ISSUE TITLE
NullPointerException updating Scoreboard timer

### ISSUE THREAD

**Issue by LogGits** [A5H73Y/Parkour#158]
Randomly started getting this error spammed in console:
```
[18:29:45] [Server thread/WARN]: [Parkour] Task #1366759 for Parkour v5.3 generated an exception
java.lang.NullPointerException: null
	at me.A5H73Y.Parkour.Managers.ScoreboardManager.updateScoreboardTimer(ScoreboardManager.java:94) ~[?:?]
	at me.A5H73Y.Parkour.Player.ParkourSession$1.run(ParkourSession.java:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by A5H73Y** [comment]
Completed as part of #168.
