### ISSUE TITLE
The plugin is running normally, but keeps reporting errors

### ISSUE THREAD

**Issue by Shizuri23** [A5H73Y/Parkour#346]
`[13:42:26 ERROR]: Could not pass event PlayerQuitEvent to Parkour v7.2.0
java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @1cf4f579)
        at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.isBanned(CraftPlayer.java:1631) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at io.github.a5h73y.parkour.listener.PlayerListener.onPlayerDisconnect(PlayerListener.java:254) ~[Parkour-7.2.0-RELEASE.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor693.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:git-Leaves-"0fab274"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:628) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:610) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2137) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2111) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:818) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1598) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1176) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaves-1.20.1.jar:git-Leaves-"0fab274"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:42:26 ERROR]: [Plan] Ran into ClassCastException - logged to plugins/Plan/logs/ClassCastException-7d20668ae3.txt
[13:42:26 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[13:42:26 ERROR]: [Plan] Error msg: "class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @1cf4f579)"`

The plugin has been working fine
This server is running Leaves version git-Leaves-"0fab274" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0fab274)

**Comment by A5H73Y** [comment]
This was a Paper bug which has now been fixed: https://github.com/PaperMC/Paper/pull/9450
I assume this will be slowly rolled out to Paper releases and any dependent projects.
