### ISSUE TITLE
A JSONObject text must begin with '{' 

### ISSUE THREAD

**Issue by smscentras** [A5H73Y/Parkour#348]
[15:44:31 WARN]: de.leonhard.storage.shaded.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.shaded.json.JSONTokener.syntaxError(JSONTokener.java:501)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.shaded.json.JSONObject.<init>(JSONObject.java:208)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.Json.readToMap(Json.java:110)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.internal.FlatFile.forceReload(FlatFile.java:296)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.Json.<init>(Json.java:68)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.type.player.PlayerConfig.<init>(PlayerConfig.java:41)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.type.player.PlayerConfig.getConfig(PlayerConfig.java:58)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getPlayerPlaceholderValue(ParkourPlaceholders.java:151)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.retrieveValue(ParkourPlaceholders.java:98)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.onRequest(ParkourPlaceholders.java:78)
[15:44:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[15:44:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[15:44:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:349)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:310)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:468)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$update$6(Hologram.java:669)
[15:44:31 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.update(Hologram.java:669)
[15:44:31 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:677)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:316)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[15:44:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[15:44:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:44:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:44:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:44:31 WARN]: de.leonhard.storage.shaded.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.shaded.json.JSONTokener.syntaxError(JSONTokener.java:501)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.shaded.json.JSONObject.<init>(JSONObject.java:208)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.Json.readToMap(Json.java:110)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.internal.FlatFile.forceReload(FlatFile.java:296)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//de.leonhard.storage.Json.<init>(Json.java:68)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.type.player.PlayerConfig.<init>(PlayerConfig.java:41)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.type.player.PlayerConfig.getConfig(PlayerConfig.java:58)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getPlayerPlaceholderValue(ParkourPlaceholders.java:151)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.retrieveValue(ParkourPlaceholders.java:98)
[15:44:31 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.onRequest(ParkourPlaceholders.java:78)
[15:44:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[15:44:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[15:44:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:349)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:310)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:468)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$update$6(Hologram.java:669)
[15:44:31 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.update(Hologram.java:669)
[15:44:31 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:677)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:316)
[15:44:31 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[15:44:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[15:44:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:44:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:44:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:45:28 WARN]: java.lang.NullPointerException
[15:45:28 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[15:45:28 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[15:45:28 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
[15:45:28 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
[15:45:28 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
[15:45:28 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
[15:45:28 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
[15:45:28 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[15:45:28 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.utility.cache.GenericCache.getExpiredKeys(GenericCache.java:50)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.utility.cache.GenericCache.clean(GenericCache.java:36)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.utility.cache.GenericCache.get(GenericCache.java:70)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getOrRetrieveCache(ParkourPlaceholders.java:492)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getCourseRecord(ParkourPlaceholders.java:442)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getCourseLeaderboardPlaceholderValue(ParkourPlaceholders.java:408)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.retrieveValue(ParkourPlaceholders.java:117)
[15:45:28 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.onRequest(ParkourPlaceholders.java:78)
[15:45:28 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[15:45:28 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[15:45:28 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:349)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:310)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:468)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$update$6(Hologram.java:669)
[15:45:28 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.update(Hologram.java:669)
[15:45:28 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:677)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:316)
[15:45:28 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[15:45:28 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[15:45:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:45:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:45:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:45:28 WARN]: Caused by: java.lang.NullPointerException

**Comment by smscentras** [comment]
[16:18:38 WARN]: java.lang.NullPointerException
[16:18:38 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[16:18:38 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[16:18:38 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
[16:18:38 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
[16:18:38 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
[16:18:38 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
[16:18:38 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
[16:18:38 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[16:18:38 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.utility.cache.GenericCache.getExpiredKeys(GenericCache.java:50)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.utility.cache.GenericCache.clean(GenericCache.java:36)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.utility.cache.GenericCache.get(GenericCache.java:70)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getOrRetrieveCache(ParkourPlaceholders.java:492)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getCourseRecord(ParkourPlaceholders.java:442)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.getCourseLeaderboardPlaceholderValue(ParkourPlaceholders.java:408)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.retrieveValue(ParkourPlaceholders.java:117)
[16:18:38 WARN]:        at Parkour-7.2.1-RELEASE.jar//io.github.a5h73y.parkour.ParkourPlaceholders.onRequest(ParkourPlaceholders.java:78)
[16:18:38 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[16:18:38 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[16:18:38 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:349)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:310)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:468)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$update$6(Hologram.java:669)
[16:18:38 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.update(Hologram.java:669)
[16:18:38 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:677)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:316)
[16:18:38 WARN]:        at DecentHolograms-2.8.3.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[16:18:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:18:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:18:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:18:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[16:18:38 WARN]: Caused by: java.lang.NullPointerException

**Comment by smscentras** [comment]
I have 8 leaderboards and have problem.
