### ISSUE TITLE
PlayerMoveEvent Error

### ISSUE THREAD

**Issue by AntZaro** [A5H73Y/Parkour#89]
Hello. I am seeing this weird error occur, and it just spams the console really badly. I'm pretty sure I have the latest version. Any ideas what could be wrong here? 

`[12:49:06] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Parkour v4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
[12:49:06] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Parkour v4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
[12:49:06] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Parkour v4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
[12:49:06] [Async Chat Thread - #123/INFO]: [m[0;37;22m[0;30;1m[[0;37;22mDefault[0;30;1m][0;37;22mTehmatevz[m[0;37;22m: [0;37;1mHi![m
[12:49:06] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Parkour v4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
`

**Comment by A5H73Y** [comment]
Hello, 
This error is very hard to resolve without having some context; if you could fully stop / start the server so Parkour starts nicely and then see what steps it took to cause the error to start appearing?
If you want to add me on skype: iA5H73Y or join the discord Parkour support server, it will be easier for us to communicate.
Thanks

**Comment by AntZaro** [comment]
Okay, thank you. I think it only happens when someone is in a course, but I will look deeper into this in a day or two, as I will have more time. I will reply here or elsewhere with more information. Thank you for the response!

**Comment by A5H73Y** [comment]
I'm assuming due to the date this was found, there have been several updates addressing bugs since and I have had no further cases of this error, it has been fixed. Please reopen if the problem appears again.
